### ISSUE TITLE
dnssec11 does not always give consistent results

### ISSUE THREAD

**Issue by cdybedahl** [dotse/zonemaster-engine#10]
Problem detected for domain daemonic.se, Calle has a data file.

**Comment by pawal** [comment]
@cdybedahl - can you attach the data file to this issue, and explain the issue?

**Comment by cdybedahl** [comment]
No, Github only allows attaching images (as far as I was able to find out, at least). The issue is partly a missing sort when extracting hash keys, and partly bad thinking on my part when implementing the control flow. The first causes the inconsistent results (when using a Perl version of 5.18 or later), the latter makes it possible for the test to report both pass and fail.
