### ISSUE TITLE
False positive on IS_A_RECURSOR

### ISSUE THREAD

**Issue by pawal** [dotse/zonemaster-engine#108]
```
$>zonemaster-cli tirsen-aili.se
Seconds Level     Message
======= ========= =======
  13.61 WARNING   All nameservers have IPv4 addresses in the same AS (8075).
  13.61 WARNING   All nameservers have IPv6 addresses in the same AS (8075).
  13.61 WARNING   All nameservers are in the same AS (8075).
  14.31 NOTICE    192.36.144.107 returned no DS records for tirsen-aili.se.
  14.82 NOTICE    Delegation from parent to child is not properly signed (no_ds).
  15.88 NOTICE    Child has nameserver(s) not listed at parent (ns3.bdm.microsoftonline.com;ns4.bdm.microsoftonline.com).
  17.23 ERROR     Nameserver ns1.bdm.microsoftonline.com/207.46.15.59 is a recursor.
  17.36 ERROR     Nameserver ns1.bdm.microsoftonline.com/2a01:111:f406:1804::59 is a recursor.
  17.51 ERROR     Nameserver ns2.bdm.microsoftonline.com/157.56.81.41 is a recursor.
  17.66 ERROR     Nameserver ns2.bdm.microsoftonline.com/2a01:111:f406:3403::41 is a recursor.
  18.00 ERROR     Nameserver ns3.bdm.microsoftonline.com/191.232.83.138 is a recursor.
  18.29 ERROR     Nameserver ns3.bdm.microsoftonline.com/2a01:111:f406:b400::22 is a recursor.
  18.31 ERROR     Nameserver ns4.bdm.microsoftonline.com/157.55.45.9 is a recursor.
  18.35 ERROR     Nameserver ns4.bdm.microsoftonline.com/2a01:111:f406:8003::22 is a recursor.
  25.78 NOTICE    SOA 'refresh' value (10800) is less than the recommended minimum (14400).
  25.78 NOTICE    SOA 'retry' value (1800) is less than the recommended minimum (3600).
```

and then

```
$>dig a www.zonemaster.net @ns4.bdm.microsoftonline.com

; <<>> DiG 9.9.5-11-Debian <<>> a www.zonemaster.net @ns4.bdm.microsoftonline.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 35155
;; flags: qr aa rd; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4000
;; QUESTION SECTION:
;www.zonemaster.net.		IN	A

;; AUTHORITY SECTION:
www.zonemaster.net.	1	IN	SOA	ns1.bdm.microsoftonline.com. msnhst.microsoft.com. 2007070100 10800 1800 691200 3600

;; Query time: 27 msec
;; SERVER: 2a01:111:f406:8003::22#53(2a01:111:f406:8003::22)
;; WHEN: Mon Aug 17 15:51:54 CEST 2015
;; MSG SIZE  rcvd: 127
```

**Comment by vlevigneron** [comment]
You are right, but it follows NAMESERVER01 specs that could be updated
to take into account this case where NXDOMAIN is returned although it
should not...


le 17 août, Patrik Wallström a ?crit :
> ```
> $>zonemaster-cli tirsen-aili.se
> Seconds Level     Message
> ======= ========= =======
>   13.61 WARNING   All nameservers have IPv4 addresses in the same AS (8075).
>   13.61 WARNING   All nameservers have IPv6 addresses in the same AS (8075).
>   13.61 WARNING   All nameservers are in the same AS (8075).
>   14.31 NOTICE    192.36.144.107 returned no DS records for tirsen-aili.se.
>   14.82 NOTICE    Delegation from parent to child is not properly signed (no_ds).
>   15.88 NOTICE    Child has nameserver(s) not listed at parent (ns3.bdm.microsoftonline.com;ns4.bdm.microsoftonline.com).
>   17.23 ERROR     Nameserver ns1.bdm.microsoftonline.com/207.46.15.59 is a recursor.
>   17.36 ERROR     Nameserver ns1.bdm.microsoftonline.com/2a01:111:f406:1804::59 is a recursor.
>   17.51 ERROR     Nameserver ns2.bdm.microsoftonline.com/157.56.81.41 is a recursor.
>   17.66 ERROR     Nameserver ns2.bdm.microsoftonline.com/2a01:111:f406:3403::41 is a recursor.
>   18.00 ERROR     Nameserver ns3.bdm.microsoftonline.com/191.232.83.138 is a recursor.
>   18.29 ERROR     Nameserver ns3.bdm.microsoftonline.com/2a01:111:f406:b400::22 is a recursor.
>   18.31 ERROR     Nameserver ns4.bdm.microsoftonline.com/157.55.45.9 is a recursor.
>   18.35 ERROR     Nameserver ns4.bdm.microsoftonline.com/2a01:111:f406:8003::22 is a recursor.
>   25.78 NOTICE    SOA 'refresh' value (10800) is less than the recommended minimum (14400).
>   25.78 NOTICE    SOA 'retry' value (1800) is less than the recommended minimum (3600).
> ```
> 
> and then
> 
> ```
> $>dig a www.zonemaster.net @ns4.bdm.microsoftonline.com
> 
> ; <<>> DiG 9.9.5-11-Debian <<>> a www.zonemaster.net @ns4.bdm.microsoftonline.com
> ;; global options: +cmd
> ;; Got answer:
> ;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 35155
> ;; flags: qr aa rd; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1
> ;; WARNING: recursion requested but not available
> 
> ;; OPT PSEUDOSECTION:
> ; EDNS: version: 0, flags:; udp: 4000
> ;; QUESTION SECTION:
> ;www.zonemaster.net.		IN	A
> 
> ;; AUTHORITY SECTION:
> www.zonemaster.net.	1	IN	SOA	ns1.bdm.microsoftonline.com. msnhst.microsoft.com. 2007070100 10800 1800 691200 3600
> 
> ;; Query time: 27 msec
> ;; SERVER: 2a01:111:f406:8003::22#53(2a01:111:f406:8003::22)
> ;; WHEN: Mon Aug 17 15:51:54 CEST 2015
> ;; MSG SIZE  rcvd: 127
> ```
> 
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/dotse/zonemaster-engine/issues/108

-- 
	Vincent Levigneron  A.F.N.I.C.  Vincent.Levigneron@nic.fr

**Comment by sandoche2k** [comment]
To discuss

**Comment by sandoche2k** [comment]
@pawal do you agree with @vlevigneron suggestion above?

**Comment by vlevigneron** [comment]
I just implemented the following behaviour that could be specified more or less that way:

1. Retrieve all address records for all the name servers using Method 4 and Method 5.
2. A SOA query for an almost certainly nonexistent name is sent to each name server IP address found in step 1, with the flag Recursion Desired (RD) set.
3. If any answer of the queries made in step 2 contains an RCODE with NXDOMAIN, proceed to step 4.
4. A SOA query for an existing  name is sent to the name server IP address, with the flag Recursion Desired (RD) set.
5. If answer RCODE is not equal to NXDOMAIN, this test case fails.

We should change messages content also.

**Comment by sandoche2k** [comment]
@vlevigneron will you be modifying it in the test spec... or you want me to do that?

**Comment by vlevigneron** [comment]
There are many ways to specify and implement this test. I tried to stay
in the same "spirit" (with NXDOMAIN checks) but perhaps that you or
Patrik would choose another way to specify it, so just decide the best
spec and write it.

Of course, if you think that my proposal is a reasonable one, I can more
or less cut/paste the content of my previous message in the specs of
NAMESERVER01.

le 20 nov., sandoche2k a ?crit :
> @vlevigneron will you be modifying it in the test spec... or you want me to do that?
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/dotse/zonemaster-engine/issues/108#issuecomment-158385859

-- 
	Vincent Levigneron  A.F.N.I.C.  Vincent.Levigneron@nic.fr

**Comment by sandoche2k** [comment]
I would go with your proposal as it is in the spirit of the existing spec.

We implement as it is, unless there is a contradiction from @pawal
