### ISSUE TITLE
Missing dependency Text::Capitalize

### ISSUE THREAD

**Issue by mtoma** [dotse/zonemaster-engine#109]
While installing Zonemaster from CPAN:
Failed test 'use Zonemaster;'
 at t/00-load.t line 9.
 Tried to use 'Zonemaster'.
Error:  Can't locate Text/Capitalize.pm in @INC (you may need to install the Text::Capitalize module) (@INC contains: /home/afnicreg/.cpan/build/Zonemaster-v1.0.4-n8Onir/inc /home/afnicreg/.cpan/build/Zonemaster-v1.0.4-n8Onir/blib/lib /home/afnicreg/.cpan/build/Zonemaster-v1.0.4-n8Onir/blib/arch /home/afnicreg/perl5/perlbrew/perls/perl-5.20.1/lib/site_perl/5.20.1/x86_64-linux-thread-multi /home/afnicreg/perl5/perlbrew/perls/perl-5.20.1/lib/site_perl/5.20.1 /home/afnicreg/perl5/perlbrew/perls/perl-5.20.1/lib/5.20.1/x86_64-linux-thread-multi /home/afnicreg/perl5/perlbrew/perls/perl-5.20.1/lib/5.20.1 .) at /home/afnicreg/.cpan/build/Zonemaster-v1.0.4-n8Onir/blib/lib/Zonemaster/Test/Nameserver.pm line 13, <DATA> line 20.

**Comment by mtoma** [comment]
In fact it seems Text:Capitalize is broken on CPAN

**Comment by pawal** [comment]
Yes, this is not a dependency problem on the Zonemaster module. I have notice that Text::Capitalize fails to pass all tests on MacOS, might be on other systems as well.

**Comment by mtoma** [comment]
cpan -i -f Text::Capitalize sloves the install problem

**Comment by pawal** [comment]
See issue #110.
