### ISSUE TITLE
Default log level for REFERRAL_SIZE_LARGE is DEBUG2?

### ISSUE THREAD

**Issue by pawal** [dotse/zonemaster-engine#111]
How come we ended up with DEBUG2 as the most severe log level for DELEGATION03? It should be at least a WARNING. Or is the code not reliable?

https://github.com/dotse/zonemaster/blob/master/docs/specifications/tests/Delegation-TP/delegation03.md

What I get when I dump the policy from the CLI is this:

      "REFERRAL_SIZE_LARGE" : "DEBUG2",
      "REFERRAL_SIZE_OK" : "DEBUG2",

**Comment by sandoche2k** [comment]
@vlevigneron 
Modify 
"REFERRAL_SIZE_LARGE" : "WARNING",
  "REFERRAL_SIZE_OK" : "INFO",
