### ISSUE TITLE
Does a zone with a CNAME (only) at apex exist?

### ISSUE THREAD

**Issue by cdybedahl** [dotse/zonemaster-engine#114]
A friend who works at Klarna asked me if this setup is actually OK. It _works_, that much is clear, and I can't really think of anything in the RFCs that forbids it. But Zonemaster doesn't even think the zone exists. Should it?

    Sarnath:~% zonemaster-cli email.klarna.com
    Seconds Level     Message
    ======= ========= =======
       2.43 CRITICAL  Nameservers for "klarna.com" provided no NS records for tested zone. RCODE given was NOERROR.
       2.44 CRITICAL  Not enough data about email.klarna.com was found to be able to run tests.
    Sarnath:~% dig soa email.klarna.com
    
    ; <<>> DiG 9.10.2-P4 <<>> soa email.klarna.com
    ;; global options: +cmd
    ;; Got answer:
    ;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 5555
    ;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1
    
    ;; OPT PSEUDOSECTION:
    ; EDNS: version: 0, flags:; udp: 4096
    ;; QUESTION SECTION:
    ;email.klarna.com.		IN	SOA
    
    ;; ANSWER SECTION:
    email.klarna.com.	3600	IN	CNAME	sendgrid.net.
    sendgrid.net.		21600	IN	SOA	ns10.dnsmadeeasy.com. dns.dnsmadeeasy.com. 2011112971 14400 600 1728000 180
    
    ;; Query time: 109 msec
    ;; SERVER: 195.67.199.20#53(195.67.199.20)
    ;; WHEN: Fri Sep 11 09:25:00 CEST 2015
    ;; MSG SIZE  rcvd: 128
    
    Sarnath:~% dig ns email.klarna.com
    
    ; <<>> DiG 9.10.2-P4 <<>> ns email.klarna.com
    ;; global options: +cmd
    ;; Got answer:
    ;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 65125
    ;; flags: qr rd ra; QUERY: 1, ANSWER: 7, AUTHORITY: 0, ADDITIONAL: 1
    
    ;; OPT PSEUDOSECTION:
    ; EDNS: version: 0, flags:; udp: 4096
    ;; QUESTION SECTION:
    ;email.klarna.com.		IN	NS
    
    ;; ANSWER SECTION:
    email.klarna.com.	3596	IN	CNAME	sendgrid.net.
    sendgrid.net.		38710	IN	NS	ns12.dnsmadeeasy.com.
    sendgrid.net.		38710	IN	NS	ns13.dnsmadeeasy.com.
    sendgrid.net.		38710	IN	NS	ns14.dnsmadeeasy.com.
    sendgrid.net.		38710	IN	NS	ns15.dnsmadeeasy.com.
    sendgrid.net.		38710	IN	NS	ns10.dnsmadeeasy.com.
    sendgrid.net.		38710	IN	NS	ns11.dnsmadeeasy.com.
    
    ;; Query time: 18 msec
    ;; SERVER: 195.67.199.20#53(195.67.199.20)
    ;; WHEN: Fri Sep 11 09:25:04 CEST 2015
    ;; MSG SIZE  rcvd: 197

**Comment by pawal** [comment]
As I see it, this zone gets hit by the basic02 test case. However, it is not clear from the test case that we mean at least one nameserver published in the child zone.

Also, a CNAME in the apex of the zone is clearly forbidden, section 3.6.2 RFC 1034:

    The domain system provides such a feature using the canonical name
    (CNAME) RR.  A CNAME RR identifies its owner name as an alias, and
    specifies the corresponding canonical name in the RDATA section of the
    RR.  If a CNAME RR is present at a node, no other data should be
    present; this ensures that the data for a canonical name and its aliases
    cannot be different.  This rule also insures that a cached CNAME can be
    used without checking with an authoritative server for other RR types.

**Comment by cdybedahl** [comment]
The `CNAME` RR _is_ the only RR present at the `email.klarna.se` node. So, as far as I can see, it does comply with that paragraph.

**Comment by pawal** [comment]
I have looked at the "domain" email.klarna.se now, and cannot see any NS records in the klarna.se zone, it is just simply a CNAME. Which does not make email.klarna.se something that we can test, right?

Yes, the klarna.se name servers give you a CNAME when asking for NS, but it is not clear anywhere that Zonemaster should be able to test the zone that the CNAME points to.
