### ISSUE TITLE
v1.0.5 incorrectly released on CPAN

### ISSUE THREAD

**Issue by dolmen** [dotse/zonemaster-engine#115]
See [RT #107100](https://rt.cpan.org/Ticket/Display.html?id=107100)

**Comment by pawal** [comment]
Uploaded a new corrected version.

**Comment by dolmen** [comment]
Unfortunately it can not be indexed because its content conflicts with v1.0.5.tar.gz you previously uploaded.
You have to increase $VERSION.

Please also [remove](https://pause.perl.org/pause/authenquery?ACTION=delete_files) v1.0.5.tar.gz from the PAUSE account as it is useless.

**Comment by karenetheridge** [comment]
You can delete previous versions at the web interface: https://pause.perl.org/pause/authenquery?ACTION=delete_files

**Comment by pawal** [comment]
New version has been release. However, I deleted the broken v1.0.5 tar ball from the PAUSE system, and it apparently takes three days?
