### ISSUE TITLE
Consistency for "." in all messages  

### ISSUE THREAD

**Issue by sandoche2k** [dotse/zonemaster-engine#127]

**Comment by matsduf** [comment]
@matsduf updates the strings in the Swedish translations so that there is always quoting around all "domain names".
@vlevigneron  updates the strings in the English and French translations so that there is always quoting around all "domain names".

**Comment by matsduf** [comment]
The update in PR #251 will solve this issue for Swedish (sv.po).

**Comment by matsduf** [comment]
The Swedish part solved by merged #251.

**Comment by sandoche2k** [comment]
@vincent please complete the french part
