### ISSUE TITLE
DNSSEC signature expire

### ISSUE THREAD

**Issue by pawal** [dotse/zonemaster-engine#13]
_From @tobbe-eklov on January 21, 2015 8:7_

Hi, I miss the DNSSEC signature expire who dnscheck prints out.

Example from dnscheck
INFO DNSSEC signature expires at: Fri Mar  6 15:35:01 2015

It would be nice to have it printed out when in 
--level INFO --raw 
mode and with SOA and DNSKEY's separate printed out

And if expire for NS, MX and ev. www RR also is printed out it's great!
  
/Tobbe

_Copied from original issue: dotse/zonemaster-cli#6_

**Comment by sandoche2k** [comment]
@vlevigneron - do you think it could be finished before .2 (15/06/2015)?

If yes, how much time you need to complete this task and the prospective date that you expect the task to be finished.

**Comment by cdybedahl** [comment]
This one is similar to #79. It might be convenient to fix both at the same time.

**Comment by vlevigneron** [comment]
OK, I'll modify the output to show this information.

2015-06-08 14:49 GMT+02:00 Calle Dybedahl <notifications@github.com>:
