### ISSUE TITLE
Classless in-addr.arpa

### ISSUE THREAD

**Issue by pawal** [dotse/zonemaster-engine#14]
_From @tobbe-eklov on January 22, 2015 7:36_

Hi, sometime's it fails with in-addr.arpa

Ex.

zonemaster-cli --level INFO --raw torsas.se

gives:

 3.53 WARNING   ADDRESS:NAMESERVER_IP_WITHOUT_REVERSE address=62.20.107.197, ns=dns.torsas.se

But there is a classless in-addr.arpa

host 62.20.107.197
197.107.20.62.in-addr.arpa is an alias for 197.192-27.107.20.62.in-addr.arpa.
197.192-27.107.20.62.in-addr.arpa domain name pointer ns.torsas.se.
197.192-27.107.20.62.in-addr.arpa domain name pointer dns.torsas.se.

/Tobbe

_Copied from original issue: dotse/zonemaster#301_

**Comment by pawal** [comment]
Have you tried this fix @tobbe-eklov?

**Comment by tobbe-eklov** [comment]
Yep, it seems to work ok!

/Tobbe
