### ISSUE TITLE
When testing a zone with 2 NS that point to the same IP...

### ISSUE THREAD

**Issue by einar** [dotse/zonemaster-engine#140]
...you correctly get a NOTICE due to DELEGATION02 that says "SAME_IP_ADDRESS" (this is cool and actually more detailed than DNSCheck), the problem is that DELEGATION01 has already passed this domain as this test only checks the names then continues.

So what Zonemaster misses is that this domain only has 1 NS, this is not the case with DNSCheck so something's missing.

You can try on "rayceem.com" for example.

**Comment by matsduf** [comment]
Update the specification of DELEGATION01 to make sure that the meaning is clear and cannot be missunderstood what "at lease two nameservers" mean.

**Comment by sandoche2k** [comment]
Rather the modification should be done at DELEGATION 02 to check for a minimum of two IP addresses.

**Comment by sandoche2k** [comment]
@vlevigneron updated the test specification https://github.com/dotse/zonemaster/pull/478

**Comment by sandoche2k** [comment]
Update the error message from "Notice" to "Error" as discussed during the F2F on 27th Nov.

**Comment by sandoche2k** [comment]
@vlevigneron thanks for resolving this issue.

**Comment by sandoche2k** [comment]
closed by PR #360
