### ISSUE TITLE
French translation 

### ISSUE THREAD

**Issue by jpierre03** [dotse/zonemaster-engine#144]
File : 
https://github.com/dotse/zonemaster-engine/blob/master/share/fr_FR.UTF-8.po

Actual translation : 

~~~perl
#: ZONE:MX_RECORD_EXISTS
msgid  "Target ({info}) found to deliver e-mail for the domain name."
msgstr "Aucune cible ({info}) n'a été trouvée pour faire parvenir un message à ce nom de domaine."
~~~~

"Aucune cible n'a été trouvée" means "No target found".

But according to https://github.com/dotse/zonemaster-engine/blob/master/lib/Zonemaster/Test/Zone.pm this label is shown when `MX_RECORD_EXISTS`

It should be
"Information ({info}) trouvée pour faire parvenir un message à ce nom de domaine."

**Comment by vlevigneron** [comment]
Bien vu... La traduction à la chaîne, ça laisse passer quelques coquille malencontreuses... je me suis permis de reprendre votre proposition de tradustion.

Je patch cela ASAP.

Merci.

**Comment by HLFH** [comment]
Coucou. @vlevigneron. Pourquoi sur zonemaster.fr, on a toujours l'erreur de traduction ? https://zonemaster.fr/test/1f2cd3d9cc956080

> Aucune cible [...] n'a été trouvée pour faire parvenir un message à ce nom de domaine.
