### ISSUE TITLE
Delegation issue : existing glue record with invalid content 

### ISSUE THREAD

**Issue by jpierre03** [dotse/zonemaster-engine#148]
According to https://github.com/dotse/zonemaster-engine/blob/master/lib/Zonemaster/Test/Delegation.pm, the DNS "glue records" of an area must exist but there is no check about content.
So glue record may have different values than those specified in the area.

http://dnsviz.net/ report such a situation as a warning.
Zonecheck say nothing about it.

What about a new test ?

This check specification could be something like : 

forall glue in gluerecords, forall ns in nameservers,
       glue_{IPv4} = ns _{IPv4} 
and glue_{IPv6} = ns _{IPv6}

![image](https://cloud.githubusercontent.com/assets/954536/11156886/bac9e4c2-8a4e-11e5-88a9-e624e82debb7.png)

## Example from dnsviz.net : 

![image](https://cloud.githubusercontent.com/assets/954536/11155550/88f8cc22-8a46-11e5-9497-a7fd76bf6209.png)

## Note

From RFC 2181,  http://www.ietf.org/rfc/rfc2181.txt, section 5.4.1. Ranking data

"Where glue
   for the same name exists in multiple zones, and differs in value, the
   nameserver should select data from a primary zone file in preference
   to secondary, but otherwise may choose any single set of such data.
   Choosing that which appears to come from a source nearer the
   authoritative data source may make sense where that can be
   determined.  Choosing primary data over secondary allows the source
   of incorrect glue data to be discovered more readily, when a problem
   with such data exists.  Where a server can detect from two zone files
   that one or more are incorrectly configured, so as to create
   conflicts, it should refuse to load the zones determined to be
   erroneous, and issue suitable diagnostics."

**Comment by jpierre03** [comment]
[IANA](https://www.iana.org/help/nameserver-requirements) state : 

> 
> # Consistency between glue and authoritative data
> 
> For name servers that have IP addresses listed as glue, the IP addresses must match the authoritative A and AAAA records for that host.
>

**Comment by sandoche2k** [comment]
Hi Jean-Pierre,


     Thanks for your contribution. A new test spec has been added
https://github.com/sandoche2k/zonemaster/docs/specifications/tests/Consistency-TP/consistency05.md.
It will be implemented ASAP.

Sandoche.

On 27 November 2015 at 22:30, Jean-Pierre PRUNARET <notifications@github.com
