### ISSUE TITLE
EDCSA support when OpenSSL is compiled without ECDSA

### ISSUE THREAD

**Issue by pawal** [dotse/zonemaster-engine#16]
Now when Cloudflare is running with ECDSA, I tested their test domain with Zonemaster. It worked well, as expected. However, some distributions that ship OpenSSL disables ECDSA due to patent reasons (or whatever) - what happens with Zonemaster when it uses an OpenSSL without ECDSA?

Their test domain is cloudflare-dnssec-auth.com, see this blog post:
https://blog.cloudflare.com/help-us-test-our-dnssec-implementation/

**Comment by cdybedahl** [comment]
I think the DNSSEC test module will crash (which gets reported as a CRITICAL level problem) when it tries to verify the signature, but I'm not sure and I have not investigated the issue.

**Comment by pawal** [comment]
It should not crash when seeing unknown (for some degree of unknown) algorithms. What will happen if it sees algorithm ... 4711?

**Comment by cdybedahl** [comment]
Zonemaster will do what Net::LDNS does, which will do what ldns does, which will do what OpenSSL does. If OpenSSL reports a sensible error (which I have a vague memory that it doesn't for GOST), that should percolate up the chain into a failure to validate.

**Comment by cdybedahl** [comment]
As of v0.71, Net::LDNS will no longer compile without proper support for ECDSA, making this issue moot. GOST support is still not quite as required, but at least a warning will be printed if Net::LDNS is compiled without it.

**Comment by cdybedahl** [comment]
Do we know of any zone that uses DNSSEC with a GOST algorithm?

**Comment by pawal** [comment]
My research gave me two: caint.su and xn--d1aiqdcn1f.xn--p1ai

From the logs of testing caint.su:

```
  12.20 INFO      The DNSKEY with tag 697 uses algorithm number 5/(RSA/SHA1), which is OK.
  12.20 INFO      The DNSKEY with tag 33831 uses algorithm number 12/(GOST R 34.10-2001), which is OK.
  12.20 DEBUG     193.232.128.6 sent a DS record, and 195.208.25.101 a DNSKEY record.
  12.24 DEBUG     Server at 195.208.25.101 sent 2 DNSKEY records and 2 RRSIG records.
  12.24 DEBUG     Server at 213.247.247.170 sent 2 DNSKEY records and 2 RRSIG records.
  12.24 DEBUG     A signature for DNSKEY with tag 697 was correctly signed.
  12.24 DEBUG     A signature for DNSKEY with tag 33831 was correctly signed.
  12.24 DEBUG     The apex DNSKEY RRset was correcly signed.
  12.24 DEBUG     RRSIG 697 correctly signs SOA RRset.
  12.24 DEBUG     RRSIG 33831 correctly signs SOA RRset.
```

and

```
   6.42 INFO      The DNSKEY with tag 30751 uses algorithm number 8/(RSA/SHA-256), which is OK.
   6.42 INFO      The DNSKEY with tag 31825 uses algorithm number 12/(GOST R 34.10-2001), which is OK.
   6.42 DEBUG     193.232.128.6 sent a DS record, and 195.208.25.101 a DNSKEY record.
   6.46 DEBUG     Server at 195.208.25.101 sent 2 DNSKEY records and 2 RRSIG records.
   6.46 DEBUG     Server at 213.247.247.170 sent 2 DNSKEY records and 2 RRSIG records.
   6.46 DEBUG     A signature for DNSKEY with tag 30751 was correctly signed.
   6.46 DEBUG     A signature for DNSKEY with tag 31825 was correctly signed.
   6.46 DEBUG     The apex DNSKEY RRset was correcly signed.
   6.46 DEBUG     RRSIG 30751 correctly signs SOA RRset.
   6.46 DEBUG     RRSIG 31825 correctly signs SOA RRset.
   6.46 DEBUG     At least one RRSIG correctly signs the SOA RRset.
   6.51 INFO      The zone has NSEC records.
   6.51 DEBUG     At least one signature correctly signed the NSEC RRset.
   6.51 DEBUG     At least one signature correctly signed the NSEC RRset.
```

However, both also uses an algorithm that we can use (RSA-SHA1 or RSA-SHA-256), which gives us a case for this issue of checking multiple algorithms: https://github.com/dotse/zonemaster/issues/231
