### ISSUE TITLE
JSON/JSON::XS usage and requirement

### ISSUE THREAD

**Issue by jelu** [dotse/zonemaster-engine#165]
If you look at `Makefile.PL`, JSON is required and JSON::XS is recommended but:
- `lib/Zonemaster/Logger.pm` does `use JSON::XS`
- `lib/Zonemaster/Nameserver.pm` does `use JSON::XS`
- `lib/Zonemaster/Test/Nameserver.pm` uses `JSON::XS->new` when creating an object but does not use any JSON*
- `lib/Zonemaster/Logger/Entry.pm` does `use JSON` but uses `JSON::XS->new` when creating an object
- `docs/installation.md` specifies to install JSON::XS altho its just recommended

Either code and documentation should be changed so that it uses JSON (which uses JSON::XS if available) or JSON::XS should be required and used everywhere.

**Comment by vlevigneron** [comment]
Sounds reasonable to use everywhere JSON instead of JSON::XS. JSON tries to use JSON::XS by default.

**Comment by jelu** [comment]
Update `docs/installation.md` also?

**Comment by jelu** [comment]
Installation documentation is still not updated.

**Comment by sandoche2k** [comment]
i agree with @jelu the issue still has to be closed. I have made a pull request https://github.com/dotse/zonemaster-engine/pull/208

**Comment by matsduf** [comment]
The installation document is updated. Close ticket.
