### ISSUE TITLE
nameserver03 test should not perform network requests

### ISSUE THREAD

**Issue by pawal** [dotse/zonemaster-engine#168]
Please test on recorded data:
https://github.com/dotse/zonemaster-engine/pull/166

(Then I can close this pull request)

**Comment by vlevigneron** [comment]
The issue is not in nameserver03 but it has to do with the way how axfr queries are saved/restored. It does not work, for now. I did some modifications on tests files to avoid that issue but we will have to modify the way chaching system works... later on...
