### ISSUE TITLE
impossible to test domains starting with a dot (like .fr)

### ISSUE THREAD

**Issue by mtoma** [dotse/zonemaster-engine#169]
zonemaster-cli .fr
Seconds Level     Message
======= ========= =======
   0.00 CRITICAL  Domain name (.fr) has a zero-length label.
   0.00 CRITICAL  Not enough data about .fr was found to be able to run tests.

zonemaster-cli .afnic.fr
Seconds Level     Message
======= ========= =======
   0.00 CRITICAL  Domain name (.afnic.fr) has a zero-length label.
   0.00 CRITICAL  Not enough data about .afnic.fr was found to be able to run tests.

**Comment by pawal** [comment]
Isn't this as designed? You cannot resolve a name like that either.

**Comment by mtoma** [comment]
No idea.
I created this issue on Sandoches request probably more for discussion than anything else.

----- Original Message -----

**Comment by pawal** [comment]
@sandoche2k Do you think this is important for usability? (I don't think so.)

**Comment by sandoche2k** [comment]
The question arised when we were testing for a TLD (for e.g. ".fr").

After your response, i think it is not needed. I think we can close this
issue @mtoma
