### ISSUE TITLE
To be able to choose a policy the Engine must be able to list available ones

### ISSUE THREAD

**Issue by einar** [dotse/zonemaster-engine#172]
As subject says, it's crucial that the Engine can output all available policies so that whatever uses it (Like the CLI or the API) can easily find them.

**Comment by pawal** [comment]
The engine is not aware of any policies, they are given as input from a default file somewhere. Other tools such as the CLI and any other backend software can give the engine another policy.

**Comment by einar** [comment]
So all tools using the Engine needs hardcoded paths that may also be OS-dependant? Ideally I think policies should follow the Engine so that all other tools can easily access them imho... This makes installation and maintenance quite a bit worse... ;p But is this decided? Then we need hardcoded paths in our API as well (and I guess we need to install the CLI just to get the policies?).

**Comment by pawal** [comment]
That is one way to put it. The other way to put it is that the Engine has no way of telling that there are other policies available. We have had an extensive discussion on this.

A user deciding on changing the "default" policy use "zonemaster-cli --dump_policy > some.file", and changes some.file to contain something else, and can store it anywhere. There is no way for the engine to tell where this policy file ends up.

**Comment by einar** [comment]
The Engine could easily do both, no? Both have a directory, or whatever, with listable policies with the option of also accessing one anywhere in the filesystem (which it already has)? If we had that we wouldnt have to have hardcoded paths in every (future) tool using the Engine for "normal uses" and we'd have automatic functionality (no need to hardcode MORE stuff) if/when we add a policy later.

Hardcoded paths should be avoided at all costs IMHO, especially when you need several of them for normal use... :p But if this is what we want then we need to hardcode paths into the API and create a more complex install instruction with said hardcoded paths... I really wanted to avoid that. :p

**Comment by pawal** [comment]
What you have now is that the engine searches for a policy in these directories, in this search order

* dist_dir( 'Zonemaster' ); # this is from prefix in the installation
* /etc/zonemaster
* /usr/local/etc/zonemaster
* $HOME/.zonemaster

The files that are searched for is config.json and policy.json.

Is your proposal that for each directory we can look for files, to have a subdirectory for policy files, and return all of them? Which one should be the default?

I believe your proposal is more complex than the current situation, where a very few tools will have a set of policies that they are using.

**Comment by einar** [comment]
I think the Engine should use one directory, like the prefix one from the installation, and be able to list the policy-files from only that directory; yes. Then we could, in the API for example, use that feature of the Engine and say that additional files should reside there instead of saying "put the addtional file somewhere and point at it in the API's configuration".

I'd rather have (the possibility of using) one logic for finding and using policies than 3 separate ones (Engine needs one, CLI and now the API). :p But if you consider this a bad idea we will implement hardcoded paths in the API.

**Comment by pawal** [comment]
I prefer clients to use their own policies if they need it. If they are hardcoded or not is not up to the engine.

Good coding practices is to _not_ hardcode any things like these, but to have those kind of things in a configuration file. Changing the engine does not change this fact. The Backend can have its own configuration files providing this information.

**Comment by einar** [comment]
They *have* to be hardcoded if the Engine cannot list them and separate logic (most likely hardcoded paths) to find them has to be in every tool that wants to run Zonemaster if the Engine cannot list them (which I would consider bad practice tbh as everyone has to implement this logic to use the Engine). To have them hardcoded in a configuration is not really different from having them hardcoded somewhere else (although prettier than in running code, ofc)...

But fine, you seem to be really against this so we will hardcode file paths into the API's config and try to explain how to use that in the installation instructions.
