### ISSUE TITLE
Locale files are not generated nor installed

### ISSUE THREAD

**Issue by jelu** [dotse/zonemaster-engine#173]
There are locale files in `share` which must be generated before doing `make manifest` etc so that they will be installed and included in the distribution.

There doesn't seem to be a way to get `Module::Install` to add a custom step to `Makefile` so it should either be a step in the release management or have the files generated and included in the source repository.

```
$ perl Makefile.PL
$ make manifest
...
$ grep LC MANIFEST
$ ( cd share && make )
$ make manifest
/usr/bin/perl "-Iinc" "-MExtUtils::Manifest=mkmanifest" -e mkmanifest
Added to MANIFEST: share/locale/en/LC_MESSAGES/Zonemaster.mo
Added to MANIFEST: share/locale/fr/LC_MESSAGES/Zonemaster.mo
Added to MANIFEST: share/locale/fr_FR.UTF-8/LC_MESSAGES/Zonemaster.mo
Added to MANIFEST: share/locale/sv/LC_MESSAGES/Zonemaster.mo
```

**Comment by pawal** [comment]
I guess this is also true for the CLI and perhaps the other components?

**Comment by jelu** [comment]
No, CLI has them generated and included in the source repository.
