### ISSUE TITLE
Remove dependency on Net::IP::XS, use Net::IP

### ISSUE THREAD

**Issue by pawal** [dotse/zonemaster-engine#174]
Comment from a package maintainer:

Zonemaster seems to depend on IP::Country. This does not follow the Debian Free Software Guidelines (DFSG) since it depends on close source binary files.

Where does it depends on this, and can we remove it? (Its from the installation documentation)

**Comment by pawal** [comment]
Net::IP::XS depends on IP::Country. Switching to Net::IP helps.

**Comment by pawal** [comment]
This is the commit that introduced Net::IP::XS:
https://github.com/dotse/zonemaster-engine/commit/b0177f6a3f5451c897fa79a7393c77a413b1e28c

**Comment by pawal** [comment]
What we should do:

Use Net::IP::XS if it is available (for performance reasons), otherwise, use Net::IP (to follow DFSG). It should be easy to do this, or what do you say @vlevigneron?

**Comment by vlevigneron** [comment]
It does not seem that difficult, I have planed a Zonemaster sprint when
I'll be back from vacation (29th of february). I'll do that at this
occasion.

le 17 févr., Patrik Wallström a ?crit :
> What we should do:
> 
> Use Net::IP::XS if it is available (for performance reasons), otherwise, use Net::IP (to follow DFSG). It should be easy to do this, or what do you say @vlevigneron?
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/dotse/zonemaster-engine/issues/174#issuecomment-185167749

-- 
	Vincent Levigneron  A.F.N.I.C.  Vincent.Levigneron@nic.fr

**Comment by sandoche2k** [comment]
@mtoma and @pawal to have a look. The issue that @vlevigneron is having is due to MOOSE

**Comment by pawal** [comment]
What was your approach @vlevigneron?

Something like this worked for me, but I was not near Moose when I tried it:

```
my $rc = eval {
    require Net::IP::XS;
    1;
};

if ( $rc ) { print "Using Net::IP::XS\n"; }
```

**Comment by vlevigneron** [comment]
Yes, something like that:

package Zonemaster::Net::IP v0.0.1;

eval {
    require Net::IP::XS;
    push @ISA, qw{Net::IP::XS};
    print "use Net::IP::XS\n";
    1;
  } or do {
    require Net::IP;
    push @ISA, qw{Net::IP};
    print "use Net::IP\n";
  };

1;


And with a simple test code (that works):

use Zonemaster::Net::IP;

my $a = Zonemaster::Net::IP->new( '1.1.1.1' );

use Data::Dumper;

print Data::Dumper::Dumper($a);

print ref($a), "\n";


2016-03-21 21:44 GMT+01:00 Patrik Wallström <notifications@github.com>:

**Comment by vlevigneron** [comment]
In fact I had messages like:

You cannot coerce an attribute (address) unless its type
(Zonemaster::Net::IP) has a coercion at
/home/levigner/perl5/perlbrew/perls/perl-5.20.1/lib/site_perl/5.20.1/x86_64-linux/Moose/Exporter.pm
line 419

It is almost fixed, I forgot to modify some Moose type constraints.


2016-03-21 22:54 GMT+01:00 vincent levigneron <levigneron.vincent@gmail.com>
:

**Comment by tomhrr** [comment]
The latest version of Net::IP::XS (0.17) makes IP::Authority an optional dependency, as in Net::IP.  It has been uploaded to CPAN, but may not yet be available for download.

**Comment by pawal** [comment]
@tomhrr Thank you for this! I will let the Debian/Unbuntu package maintainer know about this as well.

**Comment by mtoma** [comment]
https://hub.docker.com/u/afniclabs/

**Comment by sandoche2k** [comment]
@vlevigneron Can you confirm this issue is solved. @pawal once it is confirmed that this issue is fixed.. can we have a release so that packaging work could proceed

**Comment by pawal** [comment]
I have not seen any recent commit fixing this issue.

**Comment by vlevigneron** [comment]
OK, I'll check that today.

le 10 mai, Patrik Wallström a ?crit :
> I have not seen any recent commit fixing this issue.
> 
> ---
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/dotse/zonemaster-engine/issues/174#issuecomment-218076918

-- 
	Vincent Levigneron  A.F.N.I.C.  Vincent.Levigneron@nic.fr

**Comment by sandoche2k** [comment]
@pawal Can you verify the pull request :https://github.com/dotse/zonemaster-engine/compare/master...vlevigneron:fix-issue-zonemaster-engine-174?expand=1

**Comment by pawal** [comment]
@sandoche2k For this I want to install on a clean machine. I don't have any set up right now, we'll see if I have time during the RIPE week that starts now.

**Comment by sandoche2k** [comment]
I am at RIPE too :-)

**Comment by matsduf** [comment]
@oerdnj : The information from tomhrr (see above in this issue) says that Net::IP::XS is no longer mandatorily dependent on IP::Authority. Will that mean that code dependent on Net::IP::XS is packeagable for Debian and Ubuntu?

**Comment by matsduf** [comment]
Net::IP::XS is now removed from the engine. Should it be reintroduced? Optional?

**Comment by sandoche2k** [comment]
Referenced to the backend
