### ISSUE TITLE
Implement updated test case dnssec02

### ISSUE THREAD

**Issue by pawal** [dotse/zonemaster-engine#187]

**Comment by vlevigneron** [comment]
Will be implemented by the end of this week.

**Comment by vlevigneron** [comment]
It has been implemented (pull request will follow) but you should know that :
1. NO_DNSKEY has been raised from WARNING to ERROR
2. A new return value has been added (DS_RFC4509_NOT_VALID) wich needs translation. It has been set an ERROR level.
3. We still check all DS of type 1 and 2, if present..
4. I have not yet configured intentionally broken zones, so if you know some domain names with that issue, you are welcomed to share...
