### ISSUE TITLE
Add support for test profiles

### ISSUE THREAD

**Issue by pawal** [dotse/zonemaster-engine#19]
In addition to using different policies, we need support for additional test profiles. We need to group tests that is going to be executed based on a test profile.

I.e. an IANA test profile will not execute other tests than those needed to execute exactly those test cases.

**Comment by cdybedahl** [comment]
I'm trying to figure out how we can implement this with the smallest possible change to existing code. The best I can think of is to require all test implementations to look up in the global configuration if a particular test should be performed before running it. Given that we currently have 54 test implementations, it's still a noticeable amount of work.

**Comment by cdybedahl** [comment]
So if a policy says that, for example, dnssec05 should not be run, which of these does that mean:

* dnssec05 should not be included when the DNSSEC module is asked to run all tests, but it can be run explicitly.
* dnssec05 must not be run at all, even if specifically requested (with `Zonemaster::test_method()`)?

**Comment by cdybedahl** [comment]
basic00, basic01 and basic02 will not be optional. basic03 will be.
