### ISSUE TITLE
Add Swedish translations

### ISSUE THREAD

**Issue by pawal** [dotse/zonemaster-engine#196]
Swedish translations for these strings in sv.po:

"DS record with keytag {keytag} and digest type {digtype} does not match the DNSKEY with the same tag."
"DS record with keytag {keytag} and digest type {digtype} matches the DNSKEY with the same tag."
"Existing DS with digest type 2, while they do not match DNSKEY records, prevent use of DS with digest type 1 (RFC4509, section 3)."

**Comment by matsduf** [comment]
Also see #216

**Comment by matsduf** [comment]
The update in PR #251 will solve this issue.

**Comment by matsduf** [comment]
Solved by merged #251.
