### ISSUE TITLE
No control of illegal CNAMEs

### ISSUE THREAD

**Issue by einar** [dotse/zonemaster-engine#198]
I just realized we missed to take the check of "illegal cname presence" from DNSCheck (ZoneCheck didnt have this though), my bad I must have missed it. Anyhow it can easily be seen with the domain "applegift.se" as DNSCheck correctly checks for the presence of (illegal) CNAMEs.

This is a feature, not a bug so should be classed as such. Although we did miss this check from DNSCheck.

(http://dnscheck.iis.se/?time=1459749729&id=5559502&view=advanced)

**Comment by matsduf** [comment]
Needs investigation and setup of test zones. AP to @vlevigneron to setup the test zones.

**Comment by matsduf** [comment]
Duplicate of #236.
