### ISSUE TITLE
Translation not updated on Zonemaster.fr instance

### ISSUE THREAD

**Issue by HLFH** [dotse/zonemaster-engine#201]
Coucou. @vlevigneron. Pourquoi sur zonemaster.fr, on a toujours l'erreur de traduction ? https://zonemaster.fr/test/1f2cd3d9cc956080

Aucune cible [...] n'a été trouvée pour faire parvenir un message à ce nom de domaine.
Les fichiers share/fr.po et share/fr_FR.UTF-8.po, ont-il été actualisé sur l'instance Zonemaster.fr ? Je ne crois donc pas. Serait-il possible de le faire ? Merci.

Lié à : https://github.com/dotse/zonemaster-engine/issues/144

**Comment by matsduf** [comment]
Fixed in the code. There is some issue with the installation on zonemaster.fr.

**Comment by sandoche2k** [comment]
fixed
