### ISSUE TITLE
CONNECTIVITY:NAMESERVER_NO_UDP_53 (and TCP) when ns not authoritative

### ISSUE THREAD

**Issue by pawal** [dotse/zonemaster-engine#209]
CONNECTIVITY01 (for UDP) and CONNECTIVITY02 (for TCP) tests if the nameserver responds to any DNS queries. However, it seems that the implementation of this checks if the nameserver is authoritative.

While the nameserver responds with REFUSED, the following error messages are logged:
```
  31.88 ERROR     CONNECTIVITY:NAMESERVER_NO_UDP_53 address=162.xxx.xxx.2; ns=ns1.example.com
  31.92 ERROR     CONNECTIVITY:NAMESERVER_NO_TCP_53 address=2620:xxxx::2; ns=ns1.example.com
```

(longer log of course)

DELEGATION:IS_NOT_AUTHORITATIVE logs the same thing, but more correctly, but the log level is only set to WARNING.

**Comment by matsduf** [comment]
The code should not check  the rcode, just verify that there is a DNS response.
