### ISSUE TITLE
Swedish translation needed

### ISSUE THREAD

**Issue by vlevigneron** [dotse/zonemaster-engine#216]
Need swedish translation for messages with tag:
CONSISTENCY:EXTRA_ADDRESS_PARENT
CONSISTENCY:EXTRA_ADDRESS_CHILD
CONSISTENCY:TOTAL_ADDRESS_MISMATCH
CONSISTENCY:ADDRESSES_MATCH

See https://github.com/dotse/zonemaster-engine/pull/212

**Comment by matsduf** [comment]
The update in PR #251 will solve this issue.

**Comment by matsduf** [comment]
Solved by merged #251.
