### ISSUE TITLE
Remove dependency of gettext binary at build time using CPAN installation?

### ISSUE THREAD

**Issue by matsduf** [dotse/zonemaster-engine#223]
Investigate the possiblity to remove the dependency of binary gettext at build time from CPAN. Use perl gettext instead?

**Comment by pawal** [comment]
Here are some suggestions on how to do it:
http://perladvent.org/2013/2013-12-09.html

**Comment by vlevigneron** [comment]
Look at http://search.cpan.org/~azawawi/Locale-Msgfmt-0.15/script/msgfmt.pl

**Comment by matsduf** [comment]
See #224 too.

**Comment by matsduf** [comment]
Resolved by PR #305
