### ISSUE TITLE
NSEC3 Opt-Out

### ISSUE THREAD

**Issue by stirnim** [dotse/zonemaster-engine#226]
I think the use of NSEC3 Opt-Out should cause an INFO message or even WARNING. See also https://tools.ietf.org/html/rfc6781#section-5.3.4

e.g. protonmail.ch

**Comment by sandoche2k** [comment]
@vlevigneron do you think there is a specification change needed here ?

**Comment by vlevigneron** [comment]
@sandoche2k Well, it could if we plan to add more NSEC3 checks, but in the meantimes, it can be  added to DNSSEC10 test case easily.

**Comment by sandoche2k** [comment]
@vlevigneron +1
