### ISSUE TITLE
Connectivity tests incorrectly programmed

### ISSUE THREAD

**Issue by aabdnn** [dotse/zonemaster-engine#228]
I'm running tests for a zone (179.143.in-addr.arpa), and getting the following output:

```
...
   5.70 ERROR     CONNECTIVITY:NAMESERVER_NO_UDP_53 address=193.0.9.6; ns=ns.ripe.net
   5.70 ERROR     CONNECTIVITY:NAMESERVER_NO_UDP_53 address=2001:67c:e0::6; ns=ns.ripe.net
   5.73 ERROR     CONNECTIVITY:NAMESERVER_NO_TCP_53 address=193.0.9.6; ns=ns.ripe.net
   5.73 ERROR     CONNECTIVITY:NAMESERVER_NO_TCP_53 address=2001:67c:e0::6; ns=ns.ripe.net
...
```

My understand of the connectivity tests is to see if a name server answers queries. In this specific case, the name server ns.ripe.net has the zone configured but the zone has expired, and so the responses are SERVFAIL. As far as I am concerned, the name server is answering queries, and is perfectly reachable. The fact that the RCODE is SERVFAIL should not matter. The only case in which the test should conclude that there is no connectivity is when the query times out or gets a TCP reset.

So in my opinion, the tests for connectivity are incorrect. They are incorrectly looking for the NOERROR RCODE, when in fact, any response from the name server should be interpreted as "name server is reachable", ie. a DNS ping.

**Comment by sandoche2k** [comment]
@aabdnn which version of the engine are you using?

**Comment by aabdnn** [comment]
@sandoche2k I'm using version 1.0.15 of the engine, where this bug has already been fixed. This report is a duplicate of #209 but no-one seems to have noticed it.

**Comment by sandoche2k** [comment]
Thanks. Then i am closing the issue
