### ISSUE TITLE
Even though name servers are in different AS, the notice information says that ALL IPv6 are in same AS

### ISSUE THREAD

**Issue by sandoche2k** [dotse/zonemaster-engine#233]
@vlevigneron 
From kristian@larsendata.dk

I don’t understand why i get this error.
All nameservers have IPv6 addresses in the same AS

https://zonemaster.net/test/1f72f22664d03a81

Our nameservers are in different as numbers both on IPv4 and IPv6.

**Comment by vlevigneron** [comment]
The message could be more explicit but it does not seems it's wrong. If you
read the specifications for that test case:
https://github.com/dotse/zonemaster/blob/master/docs/specifications/tests/Connectivity-TP/connectivity03.md
you will notice that we get ns from parent, we have 2 answers
ns1.gratisdns.dk and ns2.gratisdns.dk but only ns1 has an IPv6 address.

2016-10-07 17:26 GMT+02:00 sandoche2k <notifications@github.com>:

**Comment by pawal** [comment]
```
$ dig ns gratisdns.dk @a.nic.dk
;; ->>HEADER<<- opcode: QUERY; status: NOERROR; id: 14934
;; Flags: qr rd; QUERY: 1; ANSWER: 0; AUTHORITY: 5; ADDITIONAL: 9

;; QUESTION SECTION:
;; gratisdns.dk.                IN      NS

;; AUTHORITY SECTION:
gratisdns.dk.           86400   IN      NS      ns1.gratisdns.dk.
gratisdns.dk.           86400   IN      NS      ns2.gratisdns.dk.
gratisdns.dk.           86400   IN      NS      ns3.gratisdns.dk.
gratisdns.dk.           86400   IN      NS      ns4.gratisdns.dk.
gratisdns.dk.           86400   IN      NS      ns5.gratisdns.dk.

;; ADDITIONAL SECTION:
ns1.gratisdns.dk.       86400   IN      A       109.238.48.13
ns2.gratisdns.dk.       86400   IN      A       185.10.10.53
ns3.gratisdns.dk.       86400   IN      A       194.0.2.6
ns4.gratisdns.dk.       86400   IN      A       62.61.159.230
ns5.gratisdns.dk.       86400   IN      A       185.43.209.139
ns1.gratisdns.dk.       86400   IN      AAAA    2a02:9d0:3002:1::2
ns3.gratisdns.dk.       86400   IN      AAAA    2001:678:5::6
ns4.gratisdns.dk.       86400   IN      AAAA    2001:14d0::4
ns5.gratisdns.dk.       86400   IN      AAAA    2001:978:2:6f::1f:53
```

That gives you four different name servers with IPv6, with several different prefixes.

This is the debug output from Zonemaster:

```
  28.60 DEBUG     [ASN:RAW] 185.10.10.53;197495 | 185.10.10.0/24 | DK | ripencc | 2012-11-14
  28.60 DEBUG     [ASN:ANNOUNCE_BY] 185.10.10.53;197495
  28.61 DEBUG     [ASN:ANNOUNCE_IN] 185.10.10.53;185.10.10.0/24
  28.65 DEBUG     [ASN:RAW] 109.238.48.13;12617 | 109.238.48.0/24 | DK | ripencc | 2010-01-20
  28.65 DEBUG     [ASN:ANNOUNCE_BY] 109.238.48.13;12617
  28.65 DEBUG     [ASN:ANNOUNCE_IN] 109.238.48.13;109.238.48.0/24
  28.69 DEBUG     [ASN:RAW] 2a02:9d0:3002:1::2;12617 | 2a02:9d0::/32 | DK | ripencc | 2009-02-05
  28.69 DEBUG     [ASN:ANNOUNCE_BY] 2a02:9d0:3002:1::2;12617
  28.69 DEBUG     [ASN:ANNOUNCE_IN] 2a02:9d0:3002:1::2;2a02:9d0::/32
```

**Comment by Spirit55555** [comment]
```
$ dig ns naestved.dk @a.nic.dk

; <<>> DiG 9.10.3-P4 <<>> ns naestved.dk @a.nic.dk
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 28098
;; flags: qr rd; QUERY: 1, ANSWER: 0, AUTHORITY: 2, ADDITIONAL: 4
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;naestved.dk.                   IN      NS

;; AUTHORITY SECTION:
naestved.dk.            86400   IN      NS      ns1.gratisdns.dk.
naestved.dk.            86400   IN      NS      ns2.gratisdns.dk.

;; ADDITIONAL SECTION:
ns1.gratisdns.dk.       86400   IN      A       109.238.48.13
ns2.gratisdns.dk.       86400   IN      A       185.10.10.53
ns1.gratisdns.dk.       86400   IN      AAAA    2a02:9d0:3002:1::2

$ dig ns naestved.dk @ns1.gratisdns.dk

; <<>> DiG 9.10.3-P4 <<>> ns naestved.dk @ns1.gratisdns.dk
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 37742
;; flags: qr aa rd; QUERY: 1, ANSWER: 5, AUTHORITY: 0, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;naestved.dk.                   IN      NS

;; ANSWER SECTION:
naestved.dk.            43200   IN      NS      ns1.gratisdns.dk.
naestved.dk.            43200   IN      NS      ns3.gratisdns.dk.
naestved.dk.            43200   IN      NS      ns2.gratisdns.dk.
naestved.dk.            43200   IN      NS      ns5.gratisdns.dk.
naestved.dk.            43200   IN      NS      ns4.gratisdns.dk.
```

So there is mismatch between the returned number of nameservers. Maybe add a warning for that?

It is a bit confusing when the test shows you all 5 nameservers and their IPs, but only counts AS numbers based on the nameservers returned from the parent.

**Comment by matsduf** [comment]
> So there is mismatch between the returned number of nameservers. Maybe add a warning for that?

It is not generally considered to be an error when the child has more NS than the parent. I think a warning is too strong. A NOTICE that a difference has been found might be relevant. Please create a ticket in dotse/zonemaster if you want to see that change in the specifications for Zonemaster.

> It is a bit confusing when the test shows you all 5 nameservers and their IPs, but only counts AS numbers based on the nameservers returned from the parent.

Agree. Please create a ticket on that.

**Comment by sandoche2k** [comment]
@matsduf @vlevigneron @Spirit55555 pls. provide your opinion

I did discuss with @pawal regarding this issue and following are the options:

Issue 1 : AS diversity issue
=====================
1. We take into account only the nameservers from the parent. 
2. We add a more detailed explanation in connectivity03.md, in the event of less than two IPv4 or IPv6 nameserver address obtained.

Issue 2 : Mismatch in the nameservers count
===================================
When the child has more nameservers than the parent, then add a notice.

**Comment by matsduf** [comment]
**Issue 1:**

I do not think that we have to change anything in CONNECTIVITY03. We should rather change the WARNING message. Today it says "All nameservers have IPv6 addresses in the same AS". I'd suggest "All nameservers in the delegation have IPv6 addresses in the same AS".

**Issue 2:**

I think a NOTICE could be relevant, but then CONSISTENCY05 should be updated. Under "ordered description" we should add a step that tests if there are nameservers in the zone not present in the delegation.

**Comment by sandoche2k** [comment]
> I do not think that we have to change anything in CONNECTIVITY03. We should rather change the WARNING message. Today it says "All nameservers have IPv6 addresses in the same AS". I'd suggest "All nameservers in the delegation have IPv6 addresses in the same AS".

@vlevigneron - no need to modify the specification ?

> I think a NOTICE could be relevant, but then CONSISTENCY05 should be updated. Under "ordered description" we should add a step that tests if there are nameservers in the zone not present in the delegation.

@matsduf - this is the case in consistency04.md ?

**Comment by matsduf** [comment]
@sandoche2k - CONSISTENCY04 is about consistency between the child nameservers ("All authoritative name servers must serve the same NS record set"). That is not the issue here.

**Comment by sandoche2k** [comment]
@matsduf CONSISTENCY04 is about "Name server NS consistency"

**Comment by vlevigneron** [comment]
@sandoche2k Consistency04 is not "consistent" with other CONSISTENCY test cases...

The first step should be:

1. Obtain the list of address records from [Method4](../Methods.md) and
   [Method5](../Methods.md).

**Comment by vlevigneron** [comment]
@sandoche2k @matsduf message has been modified in CONNECTIVITY03. Swedish translation needed for NAMESERVERS_IPV6_WITH_UNIQ_AS,  NAMESERVERS_IPV4_WITH_UNIQ_AS and NAMESERVERS_WITH_UNIQ_AS (see en.po file)

**Comment by matsduf** [comment]
@sandoche2k and @vlevigneron, I agree that Consistency04 should be adjusted. It should use only use Method3 to get the NS records. The Test Case compares the NS records returned by the *authoritative* namesservers, i.e. the nameservers of the child zone. I can make a PR with an update tomorrow.

**Comment by vlevigneron** [comment]
@mattias-p in fact, we use Method5 instead of Method3 (methods 2 and 3 get only names instead of IP addresses, which is not relevant in this case).
I know you and @sandoche2k are in charge of the sepcs and I'm sure you will find the best way to deal with that issue before I implement it, but in the original specs, there is a reference to [RFC 1034](https://tools.ietf.org/html/rfc1034) (section  4.2.2) where we can read this:

> As the last installation step, the delegation NS RRs and glue RRs
necessary to make the delegation effective should be added to the parent
zone.  The administrators of both zones should insure that the NS and
glue RRs which mark both sides of the cut are consistent and remain so.

Perhaps it was decided to use both methods 4 and 5 because of the interpretation of this section ?

**Comment by matsduf** [comment]
@vlevigneron, if you are refering to Consistency04, it states "All authoritative name servers must serve the same NS record set". The purpose of it is to compare the NS records, not the IP addresses. I.e. method3 must be used.

**Comment by vlevigneron** [comment]
@matsduf I'm not talking about what we compare, but the way we compare it, the first step in current specs is

> Obtain the list of name servers from Method2 and Method3.

It does not work because we query addresses, it should be, as other CONSISTENCY test cases, I mean use Method4 instead of Method2 and Method5 instead of Method3. It's a copmmon mistake done in specs, you just have to remember that results of Method2 and Method3 can not be queried.

**Comment by matsduf** [comment]
@sandoche2k and @vlevigneron! After reading the Test Case again I have to admit that my comments above are not correct. The Test Case is correct, but unclear. You should extract the list of relevant nameserver by Method2 and Method3. You should get the IP addresses of those nameservers by Method4 and Method5 for nameservers whos name are in-zone and the IP addresses of the other nameservers from looking up on public Internet.

See https://github.com/dotse/zonemaster/pull/481 for a clarification.

**Comment by vlevigneron** [comment]
@matsduf and @sandoche2k what do you think of this simple change which has a wording very close to what is specified in CONSISTENCY* and NAMESERVER* and which is less ambiguous than the current one...

> 1. Retrieve all address records for all the name servers using [Method
   4](../Methods.md) and [Method 5](../Methods.md).
> 2. Retrieve the NS RR set from all the name servers IP address found 
   in step 1.
> 3. If the NS RR set is not the same from all the answers received 
   from step 2, then the test case fails.

**Comment by matsduf** [comment]
@vlevigneron, which document do you refer to? I have a suggestion for new language in CONSITENCY04 in https://github.com/dotse/zonemaster/pull/481. Please comment there if you want to suggest a change. Please note that Method4 and Method5 are not enough.

**Comment by vlevigneron** [comment]
The "problem" with this new proposal is that it describes a kind of Method6.
It is a point that has been discused in the past and I know it's a source
of confusion, but it is useless to describe a process where you first call
Method2 and Method3, then Method4 and Method5 because Method2 is included
in Method4 and Method3 is included in Method5.

2016-11-22 18:06 GMT+01:00 matsduf <notifications@github.com>:

**Comment by matsduf** [comment]
@vlevigneron, you comment https://github.com/dotse/zonemaster/pull/481, please see reply there.

**Comment by sandoche2k** [comment]
Needs discussion and maybe a change in the specification. Hence moved to 2017.1

**Comment by matsduf** [comment]
Issue fixed by PR.
