### ISSUE TITLE
RIPE reverse domain fails "basic" on testing

### ISSUE THREAD

**Issue by sandoche2k** [dotse/zonemaster-engine#239]
Testing 179.143.in-addr.arpa fails in the basic test itself

https://zonemaster.net/test/1de58fba40ae3cd7

whereas it is not the case in DNSCheck for the same domain

http://dnscheck.iis.se/?time=1478511992&id=5953948&view=basic&lang=&test=standard

**Comment by aabdnn** [comment]
This is an interesting failure. The zone 179.143.in-addr.arpa has 5 name servers at the delegation point in 143.in-addr.arpa, and 4 of them return a referral response, but only one of them fails. So zonemaster should be able to test the domain. However, it seems as if zonemaster fails immediately if it happens to query the one server that is giving a SERVFAIL response.

**Comment by matsduf** [comment]
> This is an interesting failure. The zone 179.143.in-addr.arpa has 5 name servers at the delegation point in 143.in-addr.arpa, and 4 of them return a referral response, but only one of them fails.

As far as I can see, 4 of them returns authoritative answer. One returns SERVFAIL.

**Comment by matsduf** [comment]
If I test undelegated and list all the nameservers it will work in cli. But not if run it normally.

```
$ zonemaster-cli 179.143.in-addr.arpa --locale=en_US.utf8
Seconds Level     Message
======= ========= =======
   4.15 CRITICAL  Nameservers for "143.in-addr.arpa" provided no NS records for tested zone. RCODE given was SERVFAIL.
   4.20 CRITICAL  Not enough data about 179.143.in-addr.arpa was found to be able to run tests.

$ zonemaster-cli 179.143.in-addr.arpa --ns ns.ripe.net --ns ns3.versatel.net --ns ns2.versatel.net --ns ns1.versatel.net --ns ns4.versatel.net --locale=en_US.utf8
Seconds Level     Message
======= ========= =======
   2.44 ERROR     Nameserver ns.ripe.net/193.0.9.6 did not return NS records. RCODE was SERVFAIL.
   2.45 ERROR     Nameserver ns.ripe.net/2001:67c:e0::6 did not return NS records. RCODE was SERVFAIL.
   9.01 NOTICE    There are neither DS nor DNSKEY records for the zone.
   9.01 NOTICE    The zone is not signed with DNSSEC.
   9.03 WARNING   Nameserver ns.ripe.net response is not authoritative on UDP port 53.
   9.03 WARNING   Nameserver ns.ripe.net response is not authoritative on TCP port 53.
  10.07 NOTICE    Nameserver ns.ripe.net/193.0.9.6 answered AAAA query with an unexpected rcode (SERVFAIL).
  10.08 NOTICE    Nameserver ns.ripe.net/2001:67c:e0::6 answered AAAA query with an unexpected rcode (SERVFAIL).
  11.29 NOTICE    SOA 'refresh' value (3600) is less than the recommended minimum (14400).
  11.30 NOTICE    SOA 'retry' value (900) is less than the recommended minimum (3600).
  11.62 NOTICE    No target (MX, A or AAAA record) to deliver e-mail for the domain name.
matsd@backend:~/zonedata$ 
```

**Comment by aabdnn** [comment]
Hi @matsduf. So this is an inconsistency. The cli *should* be able to run tests, based on the delegation responses from one of the parents of this zone. The error message "Not enough data about zone..." is not quite correct. Does this make sense?

**Comment by sandoche2k** [comment]
I get the following. @matsduf is the engine the latest version ?
```
zonemaster-cli 179.143.in-addr.arpa
Seconds Level     Message
======= ========= =======
   2.54 CRITICAL  Nameservers for "143.in-addr.arpa" provided no NS records for tested zone. RCODE given was SERVFAIL.
   2.54 CRITICAL  Not enough data about 179.143.in-addr.arpa was found to be able to run tests.
```
