### ISSUE TITLE
Alert if the domain does not use DNSSEC

### ISSUE THREAD

**Issue by pawal** [dotse/zonemaster-engine#25]
_From @pawal on January 30, 2015 9:52_

This issue was also documented in the [WishList for Version 2.0](https://github.com/dotse/zonemaster/blob/master/docs/requirements/WishList.md).

Alert if the domain does not use DNSSEC. Is this relevant?

_Copied from original issue: dotse/zonemaster#318_

**Comment by pawal** [comment]
_From @sandoche2k on February 1, 2015 18:51_

This was an input from Kim Minh Kaplan.

The idea is to inform the clients about good practice. We can discuss
whether we want to do DNS evangelism or not during F2F :-)

**Comment by pawal** [comment]
Low message level, NOTICE?

**Comment by sandoche2k** [comment]
Yes.. (As confirmed during F2F meeting)

**Comment by cdybedahl** [comment]
In this as well as issue #24, what does "alert" mean? For this issue, there are already messages emitted for a lack of DS, a lack of DNSKEY and for a non-working signed delegation. If none of those are enough to count as "Alert if the domain does not use DNSSEC", what would be?

**Comment by cdybedahl** [comment]
So in other words, it's entirely a user interface thing and should not be an issue in zonemaster-engine.

**Comment by sandoche2k** [comment]
You are right.
