### ISSUE TITLE
The implementation of Basic01 should only test for parent

### ISSUE THREAD

**Issue by matsduf** [dotse/zonemaster-engine#260]
In https://github.com/dotse/zonemaster/issues/447 @pawal wrote:

QUOTE
The purpose of basic01 is to find out if there is a parent for the zone. _basic02_ is to find out if there is data in the parent for the zone to be tested.

```
$> zonemaster-cli --test Basic/basic01 aldkjsdasd.se
Seconds Level     Message
======= ========= =======
   1.02 CRITICAL  Nameserver for zone se responded with NXDOMAIN to query for glue.
```

So the above result does not makes sense. However, the same test for a domain that exists:

```
$>zonemaster-cli --test Basic/basic01 apa.se
Seconds Level     Message
======= ========= =======
Looks OK.
```
UNQUOTE

The test should be if the parent (the right-side of the first dot) exits or not. Not if the domain exists of not.

**Comment by matsduf** [comment]
@sandoche2k and @vlevigneron! When I look at the issue and BASIC01 I agree that the current implementation is wrong. It should not make the difference as reported above. But I cannot think of any example where it could be stated that the parent does not exist. The root always exists.

**Comment by vlevigneron** [comment]
@matsduf I agree with you, as root always exists, the best we can do, with the
algorithm proposed, is to report, during zone testing, name of parent
zone found. We may miss the initial intent of this test.

The implementation of the proposed PR is more reasonable than the
current implementation, I guess.

le 17 avril, matsduf a ?crit :
> @sandoche2k and @vlevigneron! When I look at the issue and BASIC01 I agree that the current implementation is wrong. It should not make the difference as reported above. But I cannot think of any example where it could be stated that the parent does not exist. The root always exists.
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/dotse/zonemaster-engine/issues/260#issuecomment-294579817

-- 
	Vincent Levigneron  A.F.N.I.C.  Vincent.Levigneron@nic.fr

**Comment by matsduf** [comment]
Fixed by https://github.com/dotse/zonemaster-engine/pull/284
