### ISSUE TITLE
Use of uninitialized value in Nameserver.pm

### ISSUE THREAD

**Issue by matsduf** [dotse/zonemaster-engine#267]
The following warning was emitted:

`Use of uninitialized value $answer2_string in string eq at /usr/local/share/perl/5.18.2/Zonemaster/Test/Nameserver.pm line 726.`

`$answer2_string` is created undefined on line 712, and can still be undefined in line 726.

From Nameserver.pm:

```
   712          my $answer1_string;
   713          my $answer2_string;
   714          my $json = JSON->new->canonical->pretty;
   715          if ( $p1 and scalar $p1->answer ) {
   716  
   717              my @answer1 = map { lc $_->string } sort $p1->answer;
   718              $answer1_string = $json->encode( \@answer1 );
   719  
   720              if ( $p2 and scalar $p2->answer ) {
   721  
   722                  my @answer2 = map { lc $_->string } sort $p2->answer;
   723                  $answer2_string = $json->encode( \@answer2 );
   724              }
   725  
   726              if ( $answer1_string eq $answer2_string ) {
```

**Comment by vlevigneron** [comment]
How did you get this warning ? Not it is not relevant but I don't get it when I run tests.

**Comment by matsduf** [comment]
> How did you get this warning ? Not it is not relevant but I don't get it when I run tests.

It popped up on standard error a while after I restarted the backend.
