### ISSUE TITLE
NAMESERVER:IS_A_RECURSOR but it isn't

### ISSUE THREAD

**Issue by tobbe-eklov** [dotse/zonemaster-engine#27]
Ex. the arpa. zone gives NAMESERVER:IS_A_RECURSOR when the DNS isn't a open resolver.

NAMESERVER:IS_A_RECURSOR address=198.41.0.4, dname=xx--domain-cannot-exist.xx--illegal-syntax-tld, ns="a.root-servers.net"

/Tobbe

**Comment by cdybedahl** [comment]
We could special-case the root servers to avoid this problem. Offhand, I'm not sure if it's worth the extra code complexity.

**Comment by pawal** [comment]
Do we now how many TLD:s are hosted by the root servers?

**Comment by cdybedahl** [comment]
Of the TLDs listed at http://data.iana.org/TLD/tlds-alpha-by-domain.txt, .ARPA is the only one that has NS names ending with root-servers.net. Haven't checked by IP address, though.

**Comment by tobbe-eklov** [comment]
It's only .arpa who use them according to zonemaster and http://tldwithdnssecandipv6.se/ so I make a "grep -v arpa" in my script where I fetch all TLD's.

**Comment by cdybedahl** [comment]
Given that this issue only happens for zones that are hosted on the root servers, I'll close it for now. If it shows up again, we put in a guard for the special case then.
