### ISSUE TITLE
When Cymru returns no ASN information, the information is less informational

### ISSUE THREAD

**Issue by matsduf** [dotse/zonemaster-engine#272]
Zonemaster replies `Name servers have IPv4 addresses in the following ASs: .` when Cymru returns no information on the IP's. The message should be more informational, such as "AS cannot be determined".

Should Test Case CONNECTIVITY03 (https://github.com/dotse/zonemaster/blob/master/docs/specifications/tests/Connectivity-TP/connectivity03.md) be updated to better determine various outcomes?

```
$ zonemaster-cli  --locale en_US.utf8 platiniumtv.ro --level=DEBUG --test=CONNECTIVITY
Seconds Level     Message
======= ========= =======
   0.00 DEBUG     SYSTEM:START_TIME string=2016-12-30 00:26:26 +0100; time_t=1483053986
   0.00 DEBUG     SYSTEM:TEST_TARGET module=CONNECTIVITY; zone=platiniumtv.ro
   0.00 INFO      Using version v1.0.16 of the Zonemaster engine.
(...)
   6.39 INFO      Name servers have IPv4 addresses in the following ASs: .
   6.39 INFO      Name servers have IPv6 addresses in the following ASs: .
   6.39 DEBUG     No IPv4 nameserver address is in an AS.
   6.39 DEBUG     No IPv6 nameserver address is in an AS.
   6.39 DEBUG     No nameserver address is in an AS.
```

```
$ whois -h whois.cymru.com " -v 89.38.234.0/24"
AS      | IP               | BGP Prefix          | CC | Registry | Allocated  | AS Name
NA      | 89.38.234.0      | NA                  | RO | ripencc  | 2005-11-29 | NA
```

**Comment by d3xt3r01** [comment]
I guess a ping would help ... and if it doesn't answer, let the use know ...
A mtr with the -z flag would show up AS numbers along the way ...
Also, a cleaner and neater way would be access to a looking glass / route server and checking the as-path from there or see if it's announced ( show ip bgp ... ) .

**Comment by matsduf** [comment]
@d3xt3r01, the purpose of Test Case CONNECTIVITY03 is to determine if there is redundancy in ASNs of the nameserver IP addresses. I do not see how `ping` would help.

>A mtr with the -z flag would show up AS numbers along the way ...

Please explain.

>Also, a cleaner and neater way would be access to a looking glass / route server and checking the as-path from there or see if it's announced ( show ip bgp ... ) . 

How would such a call look like? It must be something that we could include in the software and that could be used by all users of Zonemaster.

**Comment by d3xt3r01** [comment]
Nevermind my -z reference. I just noticed ```mtr  -z google.com``` uses cymru in the background to get the AS numbers.

I guess a looking glass wouldn't be too easy to implement / maintain...

I guess an easy workaround would be to use radb ? Traceroute uses it.
```whois -h whois.radb.net 89.38.234.2 | awk '/origin:/ {print $2}' | head -n 1```

**Comment by matsduf** [comment]
It looks like the data comes from RIPE Database. Is that really updated from actual routing information? Isn't the RIPE riswhois (see #273) a better source then? The latter comes from actual routing information (BGP).

```
$ whois -h whois.radb.net 89.38.234.2 
route:          89.38.234.0/24
descr:          Platinium Star TV SRL
origin:         AS42523
mnt-by:         PLATINIUM-MNT
created:        2016-11-30T13:49:21Z
last-modified:  2016-12-10T20:55:22Z
source:         RIPE
remarks:        ****************************
remarks:        * THIS OBJECT IS MODIFIED
remarks:        * Please note that all data that is generally regarded as personal
remarks:        * data has been removed from this object.
remarks:        * To view the original object, please query the RIPE Database at:
remarks:        * http://www.ripe.net/whois
remarks:        ****************************
```

**Comment by d3xt3r01** [comment]
From what I understand, RIPE is just one of the RIRs ( Regional Internet Registry ). RIPE - Europe, APNIC - Asia Pacific, ARIN, Americas .. etc.

riswhois gathers info from Remote Route Collectors (RRCs) - software ran on various machines from what I understand .. dunno under which control.

Radb gathers its info from various big organizations registered there.

So, I'm not sure I can tell which one is better now or on the long term ... I'd say riswhois at first glance .. altough I've used radb in the past without issues...

**Comment by matsduf** [comment]
>From what I understand, RIPE is just one of the RIRs ( Regional Internet Registry ). RIPE - Europe, APNIC - Asia Pacific, ARIN, Americas .. etc.

Yes, RIPE is one of the five RIRs. It covers Europe and Western Asia.

As I understand it, Riswhois is under the control of RIPE and collects data from different sites in the world. On https://www.ripe.net/analyse/internet-measurements/routing-information-service-ris/routing-information-service-ris it says

>The RIPE NCC collects and stores Internet routing data from several locations around the globe, using the Routing Information Service (RIS), established in 2001.

I tested an IP address from the US with the different tools and in this case radb did not have any data.

```
$ whois -h whois.radb.net 156.63.96.228 
%  No entries found for the selected source(s).
```
```
$ whois -h whois.cymru.com " -v 156.63.96.228"
AS      | IP               | BGP Prefix          | CC | Registry | Allocated  | AS Name
19902   | 156.63.96.228    | 156.63.0.0/16       | US | arin     |            | NET-STATE-OHIO - Department of Administrative Services, US
```
```
$ whois -h riswhois.ripe.net -- "-M 156.63.96.228"
% This is RIPE NCC's Routing Information Service
% whois gateway to collected BGP Routing Tables, version2.0
% IPv4 or IPv6 address to origin prefix match
%
% For more information visit http://www.ripe.net/ris/riswhois.html
%
% Connected to backend ris-whois07.ripe.net

route:        156.63.0.0/16
origin:       AS19902
descr:        NET-STATE-OHIO - Department of Administrative Services, US
lastupd-frst: 2016-08-25 21:03Z  194.68.123.187@rrc07
lastupd-last: 2017-01-01 04:36Z  91.206.52.60@rrc20
seen-at:      rrc00,rrc01,rrc03,rrc04,rrc05,rrc06,rrc07,rrc10,rrc11,rrc12,rrc13,rrc14,rrc15,rrc16,rrc18,rrc19,rrc20,rrc21
num-rispeers: 181
source:       RISWHOIS
```

**Comment by vlevigneron** [comment]
While I fixed the "messages" issue, we should discuss about the specs and the use of method4 in this case. The way we get IP addresses to analyse is perhaps done on an improper way.

**Comment by matsduf** [comment]
The specification in [CONNECTIVITY03](https://github.com/dotse/zonemaster/blob/master/docs/specifications/tests/Connectivity-TP/connectivity03.md) is not appropriate. 
[Method](https://github.com/dotse/zonemaster/blob/master/docs/specifications/tests/Methods.md#method-4-obtain-glue-address-records-from-parent) fetches glue from parent which could be empty. CONNECTIVITY03 should test all addresses that name server names from the delegation resolve into (it should not use the NS set from child that could be larger).

**Comment by matsduf** [comment]
Fixed by #385.

**Comment by thomasmerz** [comment]
> Nevermind my -z reference. I just noticed `mtr -z google.com` uses cymru in the background to get the AS numbers.

Great, this solved my confusion, why my Pihole was rate-limiting itself: Because I was running a `mtr -z` for diagnosing something and this used cymru a lot (some thousand queries!).

<img width="255" alt="image" src="https://user-images.githubusercontent.com/18568381/142743071-2902521f-ede9-4c91-a29b-34d0c7f49462.png">

**Comment by thomasmerz** [comment]
See also [Reason/solution found for: Pihole is forwarding local addresses to “IP”.origin.asn.cymru.com many thousand times to upstream DNS resolvers](https://discourse.pi-hole.net/t/reason-solution-found-for-pihole-is-forwarding-local-addresses-to-ip-origin-asn-cymru-com-many-thousand-times-to-upstream-dns-resolvers/51171) on https://discourse.pi-hole.net 👍🏻
