### ISSUE TITLE
NAMESERVER:RECURSIVITY_UNDEF does not log host

### ISSUE THREAD

**Issue by pawal** [dotse/zonemaster-engine#275]
The log message NAMESERVER:RECURSIVITY_UNDEF does not log any attributes about which was the host that failed.

**Comment by sandoche2k** [comment]
@vlevigneron close the issue?

**Comment by vlevigneron** [comment]
I guess it will be automatatically close once it will be merged in master branch.

**Comment by sandoche2k** [comment]
closed by PR #311
