### ISSUE TITLE
Use JSON rather than JSON::PP

### ISSUE THREAD

**Issue by pawal** [dotse/zonemaster-engine#294]
Using JSON instead of JSON::PP will make the performance of JSON improve a lot of JSON::XS is installed. There is a significant performance degradation using JSON::PP:

JSON::PP:
```
real	1m28.337s
user	1m22.356s
sys	0m0.164s
```

JSON::XS:
```
real	0m1.552s
user	0m1.544s
sys	0m0.008s
```

**Comment by mtoma** [comment]
Attached is a detailed execution profile of a zonemaster test (perl -d:NYTProf -I ../../zonemaster-engine/lib/ -I ../lib/ zonemaster-cli --json afnic.fr)

[index-subs-excl.zip](https://github.com/dotse/zonemaster-engine/files/909459/index-subs-excl.zip)

I think the JSON::PP::encode is the only external call to JSON encode in the engine. Feel free to correct me here, I reviewed all the other JSON calls and they seem to me to be all internal JSON::PP OR XS calls.

It is called 7 times for one zonemaster test.

Here are the execution times for 100000 executions of json_encode with JSON::PP:
real    2m13,153s
user    2m13,128s
sys     0m0,000s

Here are the execution times for 100000 executions of json_encode with JSON::XS:
real    0m3,588s
user    0m3,584s
sys     0m0,000s

The duration of the json_encodee depends a lot of the complexity of the structure to encode so those tests were done on the exact same structure the engine returns in JSON format for a test.

Here is the execution time of a standard zonemaster test:
time perl -I ../../zonemaster-engine/lib/ -I ../lib/ zonemaster-cli --json afnic.fr
real    0m17,483s
user    0m3,532s
sys     0m0,072s

Here is what the detailed info about the 7 json_encode calls gives:
# spent 8.64ms (29µs+8.61) within JSON::PP::encode which was called 7 times, avg 1.23ms/call: 
# 3 times (16µs+498µs) by Zonemaster::Test::Nameserver::nameserver09 at line 720 of ../../zonemaster-engine/lib/Zonemaster/Test/Nameserver.pm, avg 171µs/call 
# 3 times (8µs+302µs) by Zonemaster::Test::Nameserver::nameserver09 at line 725 of ../../zonemaster-engine/lib/Zonemaster/Test/Nameserver.pm, avg 103µs/call 
# once (5µs+7.81ms) by Zonemaster::Logger::json at line 137 of ../../zonemaster-engine/lib/Zonemaster/Logger.pm

We can see that it is called 6 times to encode nameserver obejcts and once to encode the result.

It is clear that the nameserver objects are much simpler objects to encode that the final result and will take much less time to encode but for the simplicity and to take some margin lets consider that the json_encode is called 7 times with the same complexity as is the one to encode the final zonemaster result sutructure.

This gives me: 
1,33153 millisecond for one JSON:PP::encode call
0.03588 millisecond for one JSON:XS::encode call

The difference per call is 1,33149412 millisecond
This gives me 9.32045884 millisecond difference for 7 calls.

Lets call this a 10 ms performance gain for a test that takes 17,483 seconds.

With those numbers 100000 zonemaster tests would take 20.23 days to finish with the current JSON::PP module.

By replacing the JSON::PP module with the buggy JSON::XS module one would gain 17 minutes for 100000 zonemaster tests.

Feel free to comment or correct those numbers.

For me given the bugs that the usage of JOSN::XS gave in the past and especially the time required to track them I'm clearly against this change and think this issue can be closed.

**Comment by pawal** [comment]
I like your performance numbers, how did you perform this test in Zonemaster?

**Comment by mtoma** [comment]
U used the NytProf module:
https://augustinalareina.wordpress.com/2011/02/05/getting-started-with-develnytprof/
