### ISSUE TITLE
get_iana_address_spaces_infos.pl needs documentation

### ISSUE THREAD

**Issue by matsduf** [dotse/zonemaster-engine#299]
PR #282 adds util/get_iana_address_spaces_infos.pl but without proper documentation. That must be added.

**Comment by sandoche2k** [comment]
@sandoche2k move to 2018.0

**Comment by vlevigneron** [comment]
@matsduf @sandoche2k Do you think than --help option display in #387 is enough to close this issue ?

**Comment by matsduf** [comment]
Solved by https://github.com/dotse/zonemaster-engine/pull/387
