### ISSUE TITLE
get_iana_address_spaces_infos.pl needs to include more checks

### ISSUE THREAD

**Issue by matsduf** [dotse/zonemaster-engine#300]
PR #282 adds util/get_iana_address_spaces_infos.pl, which fetches two databases from IANA and stores them locally. The script must check things more before overwriting the present databases.

**Comment by sandoche2k** [comment]
@sandoche2k move to 2018.0

**Comment by sandoche2k** [comment]
@vlevigneron Can you check whether you could complete in 2018.1 ?

**Comment by matsduf** [comment]
Solved by https://github.com/dotse/zonemaster-engine/pull/387
