### ISSUE TITLE
IPV6_ENABLED but no IPV6_NOT_ENABLED

### ISSUE THREAD

**Issue by pawal** [dotse/zonemaster-engine#302]
There is a log message tag called IPV6_ENABLED, but no corresponding IPV6_NOT_ENABLED. Same for IPV4_ENABLED, there is no IPV4_NOT_ENABLED there either. Please add those.

**Comment by vlevigneron** [comment]
@pawal There are IPV4_DISABLED and IPV6_DISABLED messages. Do you need something changed about that or is it ok for you ?
