### ISSUE TITLE
Move Engine to new name space

### ISSUE THREAD

**Issue by matsduf** [dotse/zonemaster-engine#303]
The name space for Zonemaster Engine is Zonemaster (Zonemaster::XXX), which is confusing when the other components (CLI, Backend, GUI) have their name space under Zonemaster. Move Engine to a name space one step below, i.e. Zonemaster::Engine and all its modules below that point.

**Comment by pawal** [comment]
As an app developer using Zonemaster as the library, it is not confusing.

**Comment by matsduf** [comment]
Resolved by PR #304
