### ISSUE TITLE
Updated installation instructions on "msgfmt"?

### ISSUE THREAD

**Issue by matsduf** [dotse/zonemaster-engine#306]
With PR #305 Zonemaster Engine does not use binary msgfmt anymore. Instead there is a dependency of Locale::Msgfmt. It is stated as "required" in Makefile.PL. The dependency is only a build dependency.

Do we have to update the installation documentation to cover the change? Is package "gettext" still required for anything? Is the statement in Makefile.PL enough?

**Comment by sandoche2k** [comment]
closed by PR #305
