### ISSUE TITLE
Restore unit tests in Test-lastcases.t

### ISSUE THREAD

**Issue by matsduf** [dotse/zonemaster-engine#319]
Two unit tests have been removed (commented) in Test-lastcases.t. They should be restored or replaced with relevant tests covering the field.

> \# NEED To re-configure a recursive server
> #$zone = Zonemaster::Engine->zone( 'nameserver06-can-be-resolved.zut-root.rd.nic.fr' );
> #zone_gives_not( 'nameserver01', $zone, [q{NO_RECURSOR}] );
> #zone_gives( 'nameserver01', $zone, [q{IS_A_RECURSOR}] );

See PR #310

**Comment by sandoche2k** [comment]
@matsduf close?

**Comment by matsduf** [comment]
Resolved by #378.
