### ISSUE TITLE
Missing French translation

### ISSUE THREAD

**Issue by matsduf** [dotse/zonemaster-engine#343]
One message is not translated to French:

> $ grep "None of the following nameservers returns an upward referral" fr*.po
> fr.po:msgid  "None of the following nameservers returns an upward referral : {names}."
> fr.po:msgstr "None of the following nameservers returns an upward referral : {names}."
> fr_FR.UTF-8.po:msgid  "None of the following nameservers returns an upward referral : {names}."
> fr_FR.UTF-8.po:msgstr "None of the following nameservers returns an upward referral : {names}."

**Comment by sandoche2k** [comment]
closed by #347
