### ISSUE TITLE
Comments in PO files

### ISSUE THREAD

**Issue by mattias-p** [dotse/zonemaster-engine#358]
We use conventions in our PO files that are neither documented nor compatible with the strict format described in the [PO File documentation](https://www.gnu.org/software/gettext/manual/html_node/PO-Files.html). Specifically we have a convention to document deduplicated messages by adding empty-line-separated comment blocks without msgid and msgstr lines in a semi-consistent way.

We should consider changing our conventions so that existing tools play nice with our files. I suggest that we stop using comment blocks for deduplicated messages. Instead we could list all the deduplicated tags just before the associated msgid line in one of the following formats:

Suggestion with references:

```
#: BASIC:IPV4_DISABLED CONNECTIVITY:IPV4_DISABLED CONSISTENCY:IPV4_DISABLED
#: DELEGATION:IPV4_DISABLED NAMESERVER:IPV4_DISABLED
msgid "IPv4 is disabled, not sending \"{rrtype}\" query to {ns}/{address}."
msgstr "IPv4 is disabled, not sending \"{rrtype}\" query to {ns}/{address}."
```

Suggestion with translator-comments:

```
# BASIC:IPV4_DISABLED
# CONNECTIVITY:IPV4_DISABLED
# CONSISTENCY:IPV4_DISABLED
# DELEGATION:IPV4_DISABLED
# NAMESERVER:IPV4_DISABLED
msgid "IPv4 is disabled, not sending \"{rrtype}\" query to {ns}/{address}."
msgstr "IPv4 is disabled, not sending \"{rrtype}\" query to {ns}/{address}."
```

This affects existing PO files as well as util/extract_po.pl.

**Comment by matsduf** [comment]
@mattias-p, the po files were updated following "suggestion with reference" above by PR #362. The script `util/extract_po.pl` still creates files in the old format, but it we ever recreate the files by the script a lot of manual work is still needed (handling the translations) and this is just a minor part. I suggest that we let that script be unchanged for the time being.

**Comment by mattias-p** [comment]
Closing this issue as it's covered by #372 and #373.
