### ISSUE TITLE
Debian 8: Missing Module::Install at perl Makefile.PL

### ISSUE THREAD

**Issue by pawal** [dotse/zonemaster-engine#370]
Following the installation instructions for Debian, perl Makefile.PL failes with the message that Module::Install is missing.

**Comment by pawal** [comment]
Also, after fixing the issue above, the Makefile fails with the missing module Locale::Msgfmt.

**Comment by pawal** [comment]
Running make test, emits some error messages stating that Test::Fatal is missing.

**Comment by pawal** [comment]
make test also fails with a lot of "No plan found in TAP output".

**Comment by matsduf** [comment]
Have you tried to install the release? Debian 8 is not supported.

**Comment by pawal** [comment]
I installed the latest from Github.

In short, it works fine after fixing the missing stuff from the installation instructions.

**Comment by matsduf** [comment]
@pawal, I have installed Zonemaster::Engine on Debian 8 following the (installation instructions)[https://github.com/dotse/zonemaster-engine/blob/master/docs/Installation.md], i.e. installing it from CPAN. `Module::Install` was not installed and not required. Do you have any problem when installing from CPAN?

**Comment by pawal** [comment]
I had no problem installing and running Zonemaster Engine and CLI following the current installation instructions on a clean Debian 8 machine.

**Comment by matsduf** [comment]
That is good. Then we can close this.
