### ISSUE TITLE
No DNSSEC tests are performed when no DS is published at parent

### ISSUE THREAD

**Issue by pawal** [dotse/zonemaster-engine#38]
If there is no DS record present at the parent zone, no DNSSEC tests at all are performed. This is not according to specification.

**Comment by pawal** [comment]
The DNSSEC tests in this case only execute if I specify then directly like this:

    zonemaster-cli --level DEBUG --test DNSSEC/dnssec10 example.com

**Comment by cdybedahl** [comment]
Which specification covers this behavior?

**Comment by pawal** [comment]
dnssec01 and dnssec02 should only be executed if there is a DS published at the parent, but the other tests in the DNSSEC TP do not have those "Special procedural requirements" or "Intercase dependencies" and should be executed regardless of if there is a DS present or not.

**Comment by cdybedahl** [comment]
I'm still curious which specification it's not according to. The reasoning behind the current behavior is that a lack of a DS record is a signal that DNSSEC is not desired, and therefore should not be tested. I remember discussing this some time last year, but can't remember where, when or with who...

I have no problem with changing to the behavior you describe, but given that there is more than one "natural" behavior it would be a good idea to have the reason for the one we chose written down.

**Comment by pawal** [comment]
The reason for testing without DS is that many users use this type of software to see that everything in the zone works. Forcing the user to do pre-delegation testing for testing signatures from a DNSKEY already in the zone is not very user-friendly.

Broken signatures in a zone with a DNSKEY is something that will break the zone if anybody tries to validate the zone using that DNSKEY - for example with a resolver using this DNSKEY as a trust-anchor, or a DLV service.
