### ISSUE TITLE
Zonemaster::Test::Address crashes while testing domains "maif", "java" and "oracle"

### ISSUE THREAD

**Issue by mtoma** [dotse/zonemaster-engine#45]
[toma@zonemaster.rd.nic.fr Zonemaster_Dancer]$ zonemaster-cli maif
Seconds Level     Message
======= ========= =======
   6.95 CRITICAL  Fatal error in Zonemaster::Test::Address: Can't call method "rcode" on an undefined value at /home/toma/perl5/perlbrew/perls/perl-5.20.1/lib/site_perl/5.20.1/Zonemaster/Test/Address.pm line 156, <DATA> line 20.

  12.32 WARNING   Saw 2 SOA serial numbers.
  12.32 NOTICE    Difference between the smaller serial (1425567784) and the bigger one (1425567798) is greater than the maximum allowed (0).
  19.37 NOTICE    SOA 'refresh' value (1800) is less than the recommended one (14400).
  19.37 NOTICE    SOA 'retry' value (900) is less than the recommended one (3600).
[toma@zonemaster.rd.nic.fr Zonemaster_Dancer]$ zonemaster-cli --version
CLI version:    v1.0.0
Engine version: v1.0.2

Test module versions:
        Address: v1.0.1
        Basic: v1.0.1
        Connectivity: v1.0.1
        Consistency: v1.0.1
        DNSSEC: v1.0.2
        Delegation: v1.0.1
        Example: v1.0.1
        Nameserver: v1.0.1
        Syntax: v1.0.1
        Zone: v1.0.1

**Comment by cdybedahl** [comment]
No, it doesn't. There is a serious problem in the Address test module, but the framework knows to handle that and proceeds to the next module just fine (as can be seen from the text you include).

**Comment by mtoma** [comment]
Should I update the website with this commit?

**Comment by cdybedahl** [comment]
In my opinion, no. Git bleeding edge is significantly more likely to have problems than tagged releases (which will have been much more extensively tested with many Perl versions).

**Comment by mtoma** [comment]
Ok.
