### ISSUE TITLE
SOA_SERIAL_VARIATION max_variation always 0

### ISSUE THREAD

**Issue by pawal** [dotse/zonemaster-engine#71]
The result tag SOA_SERIAL_VARIATION results in three args, serial_min, serial_max and max_variation. From what I see, max_variation is always zero. Examples:

```
name: "lv",
result: {
  args: {
    serial_min: "1428915642",
    serial_max: "1428917429",
    max_variation: 0
  },
    tag: "SOA_SERIAL_VARIATION"
}
```

and

```
name: "as",
result: {
  tag: "SOA_SERIAL_VARIATION",
  args: {
    max_variation: 0,
    serial_min: "2015041310",
    serial_max: "2015041315"
  }
}
```

What is the purpose of max_variation? I would guess it would mean the difference between _min and _max.

**Comment by cdybedahl** [comment]
max_variation is the maximum allowed difference. This value is settable in the Zonemaster::Constants module at the moment, and I think at some point there was a discussion about making it settable from the policy.

**Comment by pawal** [comment]
Ah. Then I think it is the only args key that has meta information about the policy.

**Comment by cdybedahl** [comment]
As far as I can remember, it's also the only place where the policy directly affects the outcome of a test. We discussed it at a meeting last year, but I don't think we ever came to a firm conclusion one way or the other, and Vincent's implementation reflects the resulting uncertainty.

Should some sort of action be taken here? If so, what? If not, can I close the issue?
