### ISSUE TITLE
IPv6 AS lookup not ok?

### ISSUE THREAD

**Issue by pawal** [dotse/zonemaster-engine#75]
When testing space.net, it does not see all the ASNs.

    10.22 INFO      Name servers have IPv4 addresses in the following ASs: 5539,12337.
    10.22 INFO      Name servers have IPv6 addresses in the following ASs: 12337.
    10.22 WARNING   All nameservers IPv6 addresses are in the same AS (12337).

However, the following IPv6 addresses is used:

    ns.space.net/2001:608:0:a::1
    ns3.dns.space.net/2001:608:0:f0f::f
    ns4.dns.space.net/2001:608:0:b::1
    ns5.dns.space.net/2001:780:0:49::2

2001:608::/32 is AS5539, and 2001:780::/32 is from AS12337.

Is it the Cymry feed that is faulty? The DEBUG level from Connectivity03 does not give any information about what AS is being retrieved from any lookups.

```
   0.00 DEBUG     SYSTEM:MODULE_CALL method=connectivity03, module=Connectivity, version=v1.0.1
   5.39 INFO      Name servers have IPv4 addresses in the following ASs: 5539,12337.
   5.39 INFO      Name servers have IPv6 addresses in the following ASs: 12337.
   5.39 DEBUG     Authoritative IPv4 nameservers are in more than one AS.
   5.40 WARNING   All nameservers IPv6 addresses are in the same AS (12337).
   5.40 INFO      Domain's authoritative nameservers do not belong to the same AS.
   5.40 DEBUG     SYSTEM:MODULE_CALL_END method=connectivity03, module=Connectivity
```

**Comment by vlevigneron** [comment]
Yes, the problems seems to be on Cymru side. There are the requests done:

    dig +short f.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.f.0.f.0.0.0.0.0.8.0.6.0.1.0.0.2.origin6.asn.cymru.com. TXT
    dig +short 2.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.9.4.0.0.0.0.0.0.0.8.7.0.1.0.0.2.origin6.asn.cymru.com. TXT
    "12337 | 2001:780::/32 | DE | ripencc | 2001-12-03"
    dig +short 1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.a.0.0.0.0.0.0.0.8.0.6.0.1.0.0.2.origin6.asn.cymru.com. TXT
    dig +short 1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.b.0.0.0.0.0.0.0.8.0.6.0.1.0.0.2.origin6.asn.cymru.com. TXT

**Comment by pawal** [comment]
Thanks, I sent them a support mail on this.

**Comment by sandoche2k** [comment]
@pawal - do you want this to be in .2 or in .3?

**Comment by pawal** [comment]
It probably is not part of our code, we will have to investigate further.

Bugs should always be fix as soon as possible, IMHO.

**Comment by sandoche2k** [comment]
Ok, then we will put it in release .2.

**Comment by cdybedahl** [comment]
Team Cymru's webpages state that their source of the IP-to-ASN data is listening to BGP feed(s). I have no idea how reliable that is likely to be for IPv6, but "not very" seems quite likely given how small a part of the overall traffic IPv6 still is.

**Comment by sandoche2k** [comment]
@pawal this issue is part of release .2. Can you have a look at this and if it is not possible to complete move it to .3
